DROP SCHEMA IF EXISTS OZE CASCADE;

-- create schema
CREATE SCHEMA IF NOT EXISTS OZE;

-- create tables


CREATE TABLE OZE.TASK_TYPE
(
    TASK_TYPE_ID VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(250),
    CREATE_USER VARCHAR(50) DEFAULT CURRENT_USER,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_USER VARCHAR(50) DEFAULT CURRENT_USER,
    LAST_UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT TASK_TYPE_PK PRIMARY KEY (TASK_TYPE_ID)
);

CREATE TABLE OZE.TASK
(
    TASK_ID UUID NOT NULL,
    TITLE VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(250),
    STATUS VARCHAR(10),
    TASK_TYPE_ID VARCHAR(20) NOT NULL,
    TASK_DATE DATE DEFAULT CURRENT_DATE,
    CREATE_USER VARCHAR(50) DEFAULT CURRENT_USER,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_USER VARCHAR(50) DEFAULT current_user,
    LAST_UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT TASK_PK PRIMARY KEY (TASK_ID),
    CONSTRAINT TASK_TASK_TYPE FOREIGN KEY (TASK_TYPE_ID) REFERENCES TASK_TYPE(TASK_TYPE_ID)
);